### ISSUE TITLE
Configure issue templates for flir_camera_driver

### ISSUE THREAD

**Issue by berndpfrommer** [ros-drivers/flir_camera_driver#121]
Now that there are two drivers (ROS2 and ROS) it's unclear against which branch issues are reported. An issue template would help there.

**Comment by berndpfrommer** [comment]
@tonybaltovski I tried setting this up but when I click on "Settings->Features", there is no "Issues" section. I believe this is because I do not have sufficient privileges.

**Comment by tonybaltovski** [comment]
@berndpfrommer I updated your role level so you can enable it.
