### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by Chiwingum11** [ros-drivers/flir_camera_driver#137]
sudo apt install ros-${ROS_DISTRO}-spinnaker-camera-driver
[sudo] password for ros: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package ros-galactic-spinnaker-camera-driver

**Comment by berndpfrommer** [comment]
This package has not been released for galactic. Either upgrade to humble or compile the package from source.
