### ISSUE TITLE
error while loading shared libraries: libGenApi_gcc9_v3_0.so: cannot open shared object file

### ISSUE THREAD

**Issue by Mysterium-sch** [ros-drivers/flir_camera_driver#147]
I have the package in a noetic dockerfile. After I built and sourced devel/setup.bash I try to roslaunch the test node and get the following error. Is there anything I am doing wrong and how to I get this library included.

**Comment by berndpfrommer** [comment]
I'm not familiar with the ROS1 driver but there is a good chance that 1) cleaning the workspace, 2) installing the Spinnaker SDK, and 3) rebuilding could clear up the issue.

**Comment by Mysterium-sch** [comment]
Installing the SDK worked, thanks!
