### ISSUE TITLE
Source build of humble-devel failed

### ISSUE THREAD

**Issue by hsskailash** [ros-drivers/flir_camera_driver#156]
I am not able to figure out why the source building of this humble devel is failing. this is what i am getting. 
`colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
Starting >>> flir_camera_msgs
Starting >>> flir_camera_description
Finished <<< flir_camera_description [0.21s]                             
Finished <<< flir_camera_msgs [0.67s]                     
Starting >>> spinnaker_camera_driver
--- stderr: spinnaker_camera_driver                         
CMake Error at /usr/share/cmake-3.22/Modules/WriteBasicConfigVersionFile.cmake:43 (message):
  No VERSION specified for WRITE_BASIC_CONFIG_VERSION_FILE()
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/CMakePackageConfigHelpers.cmake:237 (write_basic_config_version_file)
  CMakeLists.txt:165 (write_basic_package_version_file)

---
Failed   <<< spinnaker_camera_driver [0.56s, exited with code 1]

Summary: 2 packages finished [1.99s]
  1 package failed: spinnaker_camera_driver
  1 package had stderr output: spinnaker_camera_driver
  1 package not processed
`

**Comment by berndpfrommer** [comment]
I have the same issue here. Something about cmake or must have changed because the CI tests passed. Whatever changed, it exposed a bug in my cmake file.
I just pushed an experimental branch (fixes_for_sync) that has a fix already. Not well tested yet so I recommend just looking at the changes to the CMakelists.txt

**Comment by berndpfrommer** [comment]
PR #157 should address this. Please reopen if the problem persists.
