### ISSUE TITLE
Inability to Retrieve Color Information from Recorded Bag Using FLIR Spinnaker Package

### ISSUE THREAD

**Issue by danicannt** [ros-drivers/flir_camera_driver#208]
Description:

We are encountering an issue when using the FLIR Spinnaker package in our ROS 2 node to record a ROS bag from a camera. The specific problem arises with the image topic, which is being compressed in the RG8 format. Upon decompressing the image, we are unable to retrieve the original color information from the /camera/image_raw topic.
Steps to Reproduce:

    Setup:
        ROS2 Humble
        A ROS 2 node configured to use the FLIR Spinnaker package.
        A camera publishing images to the /camera/image_raw topic.

    Procedure:
        Start the ROS 2 node and visualize the /camera/image_raw topic.
        Record a ROS bag using ros2 bag record /camera/image_raw/compressed.
        Ensure that the topic is being compressed using the RG8 format.
        Stop the recording after sufficient data has been captured.

    Decompression:
        Decompress the recorded bag file using the appropriate ROS 2 tools.
        Attempt to visualize or process the decompressed image data.

Expected Behavior:

The decompressed image should retain the original color information from the /camera/image_raw topic, allowing it to be visualized or processed in the same way as the live feed.
Actual Behavior:
After decompressing the recorded bag, the resulting image lacks the original color information. The image appears grayscale, and the color data present in the /camera/image_raw topic is not recovered.
Environment:

    ROS 2 Distribution: Humble
    Operating System: Ubuntu 22
    Camera Model: BFS-PGE-04S2C-CS

Is there any way of telling the node in which format the node should be compressed? Maybe we are not setting up the config correctly

**Comment by berndpfrommer** [comment]
Question: does the image show in color when directly viewing the live /camera/image_raw topic (as the driver publishes it) with e.g. rqt_image_view? If that one shows in color, it's not a FLIR driver issue, but a different problem with the processing pipeline.
Note: RG8 is not really a compressed format. Rather, it's a [Bayer image](https://en.wikipedia.org/wiki/Bayer_filter),  i.e. the grey values directly pulled off the sensor. The Bayer image is then "demosaiced" (by e.g. rqt_image_view) to produce a color image.
When you ros2 bag record the /camera/image_raw/compressed topic, the image transport framework should first debayer, then compress the image, and send the compressed image to ros2 bag record.

**Comment by berndpfrommer** [comment]
Closing this issue for lack of response.
