### ISSUE TITLE
how to get colored images?

### ISSUE THREAD

**Issue by leoheung** [ros-drivers/flir_camera_driver#211]
Hi guys, I'm using [grosshoper.yaml](https://github.com/ros-drivers/flir_camera_driver/blob/humble-devel/spinnaker_camera_driver/config/grasshopper.yaml) as my parameter file, but the images from the camera are black and white. Anyone has an idea about changing the parameters to colored?

Many thanks!

**Comment by berndpfrommer** [comment]
Please fill out the issue report template so we know what camera, ROS2 version etc you are using.

**Comment by berndpfrommer** [comment]
Closing because there is insufficient information
