### ISSUE TITLE
Timestamp set incorrectly?

### ISSUE THREAD

**Issue by themightyoarfish** [ros-drivers/flir_camera_driver#37]
These lines don't make sense to me. Since GetTimeStamp() is just the nanoseconds, but the ROS timestamp wants the `nsec` field to be the nanoseconds since `sec`, more arithmetic needs to be done here, no?

https://github.com/ros-drivers/flir_camera_driver/blob/8c2c23824916e52d3ff7812f951daa23ef475bb9/spinnaker_camera_driver/src/SpinnakerCamera.cpp#L344

**Comment by ghost** [comment]
The nanoseconds will be truncated when assigned to the uint32_t `sec`  The line below sets the `nsec`.

**Comment by IMBAfarmer09** [comment]
The `nsec` is truncated incorrectly, with values ranging form 0 to 4,294,967,295, instead of 0 to 999,999,999.

https://github.com/ros-drivers/flir_camera_driver/blob/8c2c23824916e52d3ff7812f951daa23ef475bb9/spinnaker_camera_driver/src/SpinnakerCamera.cpp#L345
