### ISSUE TITLE
Image color not Working correct

### ISSUE THREAD

**Issue by diogon01** [ros-drivers/flir_camera_driver#57]
Dears, 
I try set image color and this not working, i use the params "BayerRG8", "RGB8" and "BGR8"

My result: 
![WhatsApp Image 2020-10-09 at 17 55 26](https://user-images.githubusercontent.com/7153774/95632028-25f44800-0a5b-11eb-8899-116fadef8385.jpeg)

This my launch file.
```
<launch>
   <!-- Determine this using rosrun spinnaker_camera_driver list_cameras.
       If not specified, defaults to first camera found. -->
  <arg name="camera_name"               default="pointgrey" />
  <arg name="camera_serial"             default="" />
  <arg name="calibrated"                default="0" />
 <arg name="image_format_color_coding" value="BayerRG8" />

  <!-- When unspecified, the driver will use the default framerate as given by the
      camera itself. Use the parameter 'control_frame_rate' to enable manual frame 
      rate control, and 'frame_rate' to set the frame rate value. -->
  <arg name="control_frame_rate"        default="false" />
  <arg name="frame_rate"                default="30" />

  <group ns="$(arg camera_name)">
    <!-- Nodelet manager -->
    <node pkg="nodelet" type="nodelet" name="camera_nodelet_manager" args="manager" cwd="node" output="screen"/>

    <!-- Camera nodelet -->
    <node pkg="nodelet" type="nodelet" name="spinnaker_camera_nodelet"
          args="load spinnaker_camera_driver/SpinnakerCameraNodelet camera_nodelet_manager" >

      <param name="frame_id"                        value="camera" />
      <param name="serial"                          value="$(arg camera_serial)" />

      <!-- Frame rate -->
      <param name="acquisition_frame_rate_enable"   value="$(arg control_frame_rate)" />
      <param name="acquisition_frame_rate"          value="$(arg frame_rate)" />

      <!-- Color Format -->
	  <param name="image_format_color_coding" 		value="$(arg image_format_color_coding)" />
	  
	  
	  <!-- Use the camera_calibration package to create this file -->
      <param name="camera_info_url" if="$(arg calibrated)"
             value="file://$(env HOME)/.ros/camera_info/$(arg camera_serial).yaml" />
    </node>

    <!-- Debayering nodelet -->
    <node pkg="nodelet" type="nodelet" name="image_proc_debayer"
          args="load image_proc/debayer camera_nodelet_manager">
    </node>
  </group>
</launch>
```

**Comment by tiexuedanxin** [comment]
> Dears,
> I try set image color and this not working, i use the params "BayerRG8", "RGB8" and "BGR8"
> 
> My result:
> ![WhatsApp Image 2020-10-09 at 17 55 26](https://user-images.githubusercontent.com/7153774/95632028-25f44800-0a5b-11eb-8899-116fadef8385.jpeg)
> 
> This my launch file.
> 
> ```
> <launch>
>    
>   <arg name="camera_name"               default="pointgrey" />
>   <arg name="camera_serial"             default="" />
>   <arg name="calibrated"                default="0" />
>  <arg name="image_format_color_coding" value="BayerRG8" />
> 
>   
>   <arg name="control_frame_rate"        default="false" />
>   <arg name="frame_rate"                default="30" />
> 
>   <group ns="$(arg camera_name)">
>     
>     <node pkg="nodelet" type="nodelet" name="camera_nodelet_manager" args="manager" cwd="node" output="screen"/>
> 
>     
>     <node pkg="nodelet" type="nodelet" name="spinnaker_camera_nodelet"
>           args="load spinnaker_camera_driver/SpinnakerCameraNodelet camera_nodelet_manager" >
> 
>       <param name="frame_id"                        value="camera" />
>       <param name="serial"                          value="$(arg camera_serial)" />
> 
>       
>       <param name="acquisition_frame_rate_enable"   value="$(arg control_frame_rate)" />
>       <param name="acquisition_frame_rate"          value="$(arg frame_rate)" />
> 
>       
> 	  <param name="image_format_color_coding" 		value="$(arg image_format_color_coding)" />
> 	  
> 	  
> 	  
>       <param name="camera_info_url" if="$(arg calibrated)"
>              value="file://$(env HOME)/.ros/camera_info/$(arg camera_serial).yaml" />
>     </node>
> 
>     
>     <node pkg="nodelet" type="nodelet" name="image_proc_debayer"
>           args="load image_proc/debayer camera_nodelet_manager">
>     </node>
>   </group>
> </launch>
> ```

hello, do you know how to set the parameters for camera.

**Comment by diogon01** [comment]
> > Dears,
> > I try set image color and this not working, i use the params "BayerRG8", "RGB8" and "BGR8"
> > My result:
> > ![WhatsApp Image 2020-10-09 at 17 55 26](https://user-images.githubusercontent.com/7153774/95632028-25f44800-0a5b-11eb-8899-116fadef8385.jpeg)
> > This my launch file.
> > ```
> > <launch>
> >    
> >   <arg name="camera_name"               default="pointgrey" />
> >   <arg name="camera_serial"             default="" />
> >   <arg name="calibrated"                default="0" />
> >  <arg name="image_format_color_coding" value="BayerRG8" />
> > 
> >   
> >   <arg name="control_frame_rate"        default="false" />
> >   <arg name="frame_rate"                default="30" />
> > 
> >   <group ns="$(arg camera_name)">
> >     
> >     <node pkg="nodelet" type="nodelet" name="camera_nodelet_manager" args="manager" cwd="node" output="screen"/>
> > 
> >     
> >     <node pkg="nodelet" type="nodelet" name="spinnaker_camera_nodelet"
> >           args="load spinnaker_camera_driver/SpinnakerCameraNodelet camera_nodelet_manager" >
> > 
> >       <param name="frame_id"                        value="camera" />
> >       <param name="serial"                          value="$(arg camera_serial)" />
> > 
> >       
> >       <param name="acquisition_frame_rate_enable"   value="$(arg control_frame_rate)" />
> >       <param name="acquisition_frame_rate"          value="$(arg frame_rate)" />
> > 
> >       
> > 	  <param name="image_format_color_coding" 		value="$(arg image_format_color_coding)" />
> > 	  
> > 	  
> > 	  
> >       <param name="camera_info_url" if="$(arg calibrated)"
> >              value="file://$(env HOME)/.ros/camera_info/$(arg camera_serial).yaml" />
> >     </node>
> > 
> >     
> >     <node pkg="nodelet" type="nodelet" name="image_proc_debayer"
> >           args="load image_proc/debayer camera_nodelet_manager">
> >     </node>
> >   </group>
> > </launch>
> > ```
> 
> hello, do you know how to set the parameters for camera.

@tiexuedanxin i'm change the color white balance for `once` and this work

**Comment by ParthAD3** [comment]
Hi @diogon01 
Did you solve this problem?

**Comment by diogon01** [comment]
> Hi @diogon01
> Did you solve this problem?

Yes man, 
This work after change exposure_auto to "Once" in file white balance in the [Spinnaker.cfg](https://github.com/ros-drivers/flir_camera_driver/blob/kinetic-devel/spinnaker_camera_driver/cfg/Spinnaker.cfg) line number 85

**Comment by diogon01** [comment]
This work after change exposure_auto to "Once" in file white balance in the Spinnaker.cfg line number 85
